export const nativeDomPhrases = {
  hi: {
    'Back to Dashboard': 'डैशबोर्ड पर वापस जाएं',
    'Back to Home': 'होम पर वापस जाएं',
    Login: 'लॉगिन',
    Register: 'रजिस्टर',
    'Sign In': 'साइन इन',
    'Create Account': 'खाता बनाएं',
    'Welcome Back.': 'वापसी पर स्वागत है.',
    'Join Parivahan.': 'परिवहन से जुड़ें.',
    'Manage your transport services effortlessly.': 'अपनी परिवहन सेवाएं आसानी से प्रबंधित करें.',
    'Your journey begins here.': 'आपकी यात्रा यहां शुरू होती है.',
    'Sign in to your account': 'अपने खाते में साइन इन करें',
    'Access all your vehicle details in one place.': 'अपने सभी वाहन विवरण एक जगह देखें.',
    'Create an account': 'खाता बनाएं',
    'Join Parivahan Sewa to manage your vehicles.': 'अपने वाहनों को प्रबंधित करने के लिए परिवहन सेवा से जुड़ें.',
    'Email Address': 'ईमेल पता',
    Password: 'पासवर्ड',
    'Forgot password?': 'पासवर्ड भूल गए?',
    'Full Name': 'पूरा नाम',
    'Mobile Number': 'मोबाइल नंबर',
    'Preferred Language': 'पसंदीदा भाषा',
    'Profile Photo (Optional)': 'प्रोफाइल फोटो (वैकल्पिक)',
    'Photo selected. Click to change.': 'फोटो चुनी गई. बदलने के लिए क्लिक करें.',
    'Upload a photo (Max 2MB)': 'फोटो अपलोड करें (अधिकतम 2MB)',
    'Add Your Vehicle': 'अपना वाहन जोड़ें',
    'Link an existing vehicle to your account': 'मौजूदा वाहन को अपने खाते से लिंक करें',
    'Registration Number': 'पंजीकरण संख्या',
    'Enter your vehicle registration number without spaces.': 'बिना स्पेस के वाहन पंजीकरण संख्या दर्ज करें.',
    'Security Check': 'सुरक्षा जांच',
    'Reload CAPTCHA': 'CAPTCHA फिर से लोड करें',
    'CAPTCHA Disabled': 'CAPTCHA अक्षम है',
    'Loading CAPTCHA...': 'CAPTCHA लोड हो रहा है...',
    'Verify & Send OTP': 'सत्यापित करें और OTP भेजें',
    'Enter OTP': 'OTP दर्ज करें',
    Back: 'वापस',
    'Confirm & Link': 'पुष्टि करें और लिंक करें',
    'My Digital Documents': 'मेरे डिजिटल दस्तावेज',
    'Access your official transport documents and certificates securely.': 'अपने आधिकारिक परिवहन दस्तावेज और प्रमाणपत्र सुरक्षित रूप से देखें.',
    'Personal Documents': 'व्यक्तिगत दस्तावेज',
    'Driving License': 'ड्राइविंग लाइसेंस',
    'No Driving License Found': 'कोई ड्राइविंग लाइसेंस नहीं मिला',
    "You don't have an approved driving license on record.": 'आपके रिकॉर्ड में स्वीकृत ड्राइविंग लाइसेंस नहीं है.',
    'Apply for DL': 'DL के लिए आवेदन करें',
    'Vehicle Documents': 'वाहन दस्तावेज',
    'Registration Certificate (RC)': 'पंजीकरण प्रमाणपत्र (RC)',
    'Motor Insurance': 'मोटर बीमा',
    'PUC Certificate': 'PUC प्रमाणपत्र',
    'Road Tax': 'रोड टैक्स',
    'No Vehicles Found': 'कोई वाहन नहीं मिला',
    'Register Vehicle': 'वाहन पंजीकृत करें',
    Expired: 'समाप्त',
    Active: 'सक्रिय',
    'Valid Till': 'वैधता तक',
    Lifetime: 'आजीवन',
    'Track & Review Applications': 'आवेदन ट्रैक और समीक्षा करें',
    'Monitor the status of your submitted applications and request corrections if needed.': 'अपने जमा किए गए आवेदनों की स्थिति देखें और जरूरत हो तो सुधार मांगें.',
    'No Applications Found': 'कोई आवेदन नहीं मिला',
    "You haven't submitted any Vehicle Registration or Driving License applications yet.": 'आपने अभी तक कोई वाहन पंजीकरण या ड्राइविंग लाइसेंस आवेदन जमा नहीं किया है.',
    'Vehicle Registration': 'वाहन पंजीकरण',
    'App No:': 'आवेदन संख्या:',
    Draft: 'ड्राफ्ट',
    'Vehicle Category': 'वाहन श्रेणी',
    'Vehicle Type': 'वाहन प्रकार',
    'Inspection Date': 'निरीक्षण तिथि',
    'Applicant Name': 'आवेदक का नाम',
    'Vehicle Class': 'वाहन वर्ग',
    'Test Result': 'परीक्षा परिणाम',
    'I Found a Mistake': 'मुझे गलती मिली',
    'Corrections Center': 'सुधार केंद्र',
    'Found a mistake in your application or documents? Request a correction here.': 'अपने आवेदन या दस्तावेज में गलती मिली? यहां सुधार अनुरोध करें.',
    'Target Type': 'लक्ष्य प्रकार',
    'Target ID': 'लक्ष्य ID',
    'Incorrect Field Name': 'गलत फील्ड नाम',
    'Current Value': 'वर्तमान मान',
    'Requested Value': 'अनुरोधित मान',
    'Reason for Correction': 'सुधार का कारण',
    'Submit Correction Request': 'सुधार अनुरोध जमा करें',
    'My Correction Requests': 'मेरे सुधार अनुरोध',
    'No Requests': 'कोई अनुरोध नहीं',
    "You haven't submitted any corrections yet.": 'आपने अभी तक कोई सुधार जमा नहीं किया है.',
    'Official record updated successfully.': 'आधिकारिक रिकॉर्ड सफलतापूर्वक अपडेट हो गया.',
    'Citizen Guide': 'नागरिक गाइड',
    'Learn. Understand. Stay informed.': 'सीखें. समझें. जानकारी रखें.',
    'Simple guides to help you use vehicle services, apply for licences and register vehicles with confidence.': 'वाहन सेवाओं का उपयोग, लाइसेंस आवेदन और वाहन पंजीकरण आत्मविश्वास से करने के लिए सरल गाइड.',
    'Quick Video Guides': 'त्वरित वीडियो गाइड',
    'View all videos': 'सभी वीडियो देखें',
    'Quick Service Guides': 'त्वरित सेवा गाइड',
    'Learn more': 'और जानें',
    'Important Rules': 'महत्वपूर्ण नियम',
    "Do's & Don'ts": 'क्या करें और क्या न करें',
    "DO'S": 'करें',
    "DON'Ts": 'न करें',
    'What Should I Do If...': 'अगर ऐसा हो तो क्या करूं...',
    'Your Vehicle At A Glance': 'आपका वाहन एक नजर में',
    'Government Terms, Simplified': 'सरकारी शब्द, सरल भाषा में',
    'Information Disclaimer': 'सूचना अस्वीकरण',
    'Visit Official Parivahan Website': 'आधिकारिक परिवहन वेबसाइट देखें',
    Close: 'बंद करें',
    'Discover Next': 'अगला देखें',
    'Next guide': 'अगली गाइड',
    'Back to all guides': 'सभी गाइड पर वापस',
    'Video guide': 'वीडियो गाइड',
    'Ask My Vehicle': 'मेरे वाहन से पूछें',
    'ASK MY VEHICLE': 'मेरे वाहन से पूछें',
    'Your vehicle, explained simply.': 'आपका वाहन, सरल भाषा में.',
    'Quick Questions': 'त्वरित प्रश्न',
    'No vehicles found. Please register a vehicle first.': 'कोई वाहन नहीं मिला. पहले वाहन पंजीकृत करें.',
    'Loading vehicle...': 'वाहन लोड हो रहा है...',
    'No vehicle selected': 'कोई वाहन चयनित नहीं',
    'AI Online': 'AI ऑनलाइन',
    'New conversation': 'नई बातचीत',
    'Powered by Gemini · Answers based on your vehicle data only': 'Gemini द्वारा संचालित · उत्तर केवल आपके वाहन डेटा पर आधारित हैं',
    'Fleet Management': 'फ्लीट प्रबंधन',
    "You don't have a registered fleet yet.": 'आपके पास अभी पंजीकृत फ्लीट नहीं है.',
    'Register your fleet to track vehicles in real-time, monitor routes, and receive alerts.': 'वाहनों को रीयल-टाइम ट्रैक करने, रूट देखने और अलर्ट पाने के लिए अपनी फ्लीट पंजीकृत करें.',
    'Live GPS Tracking': 'लाइव GPS ट्रैकिंग',
    'Route Monitoring': 'रूट मॉनिटरिंग',
    'Instant Alerts': 'तुरंत अलर्ट',
    'Start Fleet Registration': 'फ्लीट पंजीकरण शुरू करें',
    'Fleet Registration Under Review': 'फ्लीट पंजीकरण समीक्षा में है',
    'Application Timeline': 'आवेदन समयरेखा',
    'Application Submitted': 'आवेदन जमा हुआ',
    'Document Verification': 'दस्तावेज सत्यापन',
    'Authority Approval': 'प्राधिकरण स्वीकृति',
    'Fleet Approved': 'फ्लीट स्वीकृत',
    'Refresh Status': 'स्थिति रीफ्रेश करें',
    'Fleet Registration Rejected': 'फ्लीट पंजीकरण अस्वीकृत',
    'Your fleet registration application was not approved.': 'आपका फ्लीट पंजीकरण आवेदन स्वीकृत नहीं हुआ.',
    'Reason for Rejection:': 'अस्वीकृति का कारण:',
    'Reapply for Fleet Registration': 'फ्लीट पंजीकरण के लिए फिर आवेदन करें',
    'Fleet Registration': 'फ्लीट पंजीकरण',
    Vehicle: 'वाहन',
    Documents: 'दस्तावेज',
    Business: 'व्यवसाय',
    Review: 'समीक्षा',
    'Application Submitted!': 'आवेदन जमा हो गया!',
    'Go to Fleet Dashboard': 'फ्लीट डैशबोर्ड पर जाएं',
    'Vehicle Information': 'वाहन जानकारी',
    'Fleet Name *': 'फ्लीट नाम *',
    'Vehicle Registration Number *': 'वाहन पंजीकरण संख्या *',
    Continue: 'जारी रखें',
    'Business Verification': 'व्यवसाय सत्यापन',
    'Business License / Trade Proof': 'व्यवसाय लाइसेंस / व्यापार प्रमाण',
    'Review & Submit': 'समीक्षा और जमा करें',
    'Submit Fleet Registration': 'फ्लीट पंजीकरण जमा करें',
    'Click to upload': 'अपलोड करने के लिए क्लिक करें',
    'JPG, PNG, PDF · Max 5MB': 'JPG, PNG, PDF · अधिकतम 5MB',
    'Fleet Dashboard': 'फ्लीट डैशबोर्ड',
    "Welcome back! Here's what's happening with your fleet.": 'वापसी पर स्वागत है! आपकी फ्लीट में क्या हो रहा है.',
    Fleet: 'फ्लीट',
    Online: 'ऑनलाइन',
    Offline: 'ऑफलाइन',
    'At Risk': 'जोखिम में',
    'Risk Alerts': 'जोखिम अलर्ट',
    'Active Routes': 'सक्रिय रूट',
    'Live Fleet Map': 'लाइव फ्लीट मैप',
    'No GPS data available': 'GPS डेटा उपलब्ध नहीं',
    'View Fullscreen': 'पूर्ण स्क्रीन देखें',
    'Vehicle List': 'वाहन सूची',
    'Search vehicle...': 'वाहन खोजें...',
    'Vehicle Number': 'वाहन संख्या',
    'Make / Model': 'मेक / मॉडल',
    Status: 'स्थिति',
    'Current Route': 'वर्तमान रूट',
    Speed: 'गति',
    'Last Updated': 'अंतिम अपडेट',
    'No vehicles match your criteria.': 'आपके मानदंड से कोई वाहन मेल नहीं खाता.',
    'View All Vehicles': 'सभी वाहन देखें',
    'Fleet Risk Radar': 'फ्लीट जोखिम रडार',
    Critical: 'गंभीर',
    Warning: 'चेतावनी',
    Normal: 'सामान्य',
    'Active Alerts': 'सक्रिय अलर्ट',
    'View All': 'सभी देखें',
    'No active alerts.': 'कोई सक्रिय अलर्ट नहीं.',
    'Quick Actions': 'त्वरित कार्य',
    'Create Route': 'रूट बनाएं',
    'Add Vehicle': 'वाहन जोड़ें',
    'View Reports': 'रिपोर्ट देखें',
    'Send Alert': 'अलर्ट भेजें',
    'Create New Route': 'नया रूट बनाएं',
    'Vehicle Registration Number': 'वाहन पंजीकरण संख्या',
    'Start Location': 'शुरुआती स्थान',
    Destination: 'गंतव्य',
    Cancel: 'रद्द करें',
    'Start Monitoring': 'मॉनिटरिंग शुरू करें',
    'Coming Soon': 'जल्द आ रहा है',
    'This feature is currently under development and will be available in a future update.': 'यह सुविधा अभी विकास में है और भविष्य के अपडेट में उपलब्ध होगी.',
    'Got it': 'समझ गया',
    'Guardian Mode': 'गार्जियन मोड',
    'Register your vehicle': 'अपना वाहन पंजीकृत करें',
    'Guardian Mode starts after a vehicle is linked to your account.': 'वाहन खाते से लिंक होने के बाद गार्जियन मोड शुरू होता है.',
    'Keep your vehicle safe. Get notified if it leaves the safe zone.': 'अपने वाहन को सुरक्षित रखें. सुरक्षित क्षेत्र से बाहर जाने पर सूचना पाएं.',
    ON: 'चालू',
    OFF: 'बंद',
    'Your vehicle is protected': 'आपका वाहन सुरक्षित है',
    'Set safe zone to protect': 'सुरक्षा के लिए सुरक्षित क्षेत्र सेट करें',
    'Set your vehicle location safe zone': 'वाहन स्थान का सुरक्षित क्षेत्र सेट करें',
    'Set Safe Location': 'सुरक्षित स्थान सेट करें',
    'Safe Location': 'सुरक्षित स्थान',
    'Change Location': 'स्थान बदलें',
    'Safe Zone Radius': 'सुरक्षित क्षेत्र त्रिज्या',
    'Alert Preference': 'अलर्ट पसंद',
    'Manage Alerts': 'अलर्ट प्रबंधित करें',
    'Quiet Hours': 'शांत समय',
    Edit: 'संपादित करें',
    Area: 'क्षेत्र',
    Coordinates: 'निर्देशांक',
    'Save Location': 'स्थान सहेजें',
    'Alert Channels': 'अलर्ट चैनल',
    'Push notifications': 'पुश सूचनाएं',
    'SMS alerts': 'SMS अलर्ट',
    'Email alerts': 'ईमेल अलर्ट',
    'Save Alerts': 'अलर्ट सहेजें',
    'Enable quiet hours': 'शांत समय सक्षम करें',
    'Save Quiet Hours': 'शांत समय सहेजें',
    'Run Geofence Check': 'जियोफेंस जांच चलाएं',
    'Breach Detected': 'उल्लंघन मिला',
    'Inside Safe Zone': 'सुरक्षित क्षेत्र में',
    'Recent Guardian Events': 'हालिया गार्जियन घटनाएं',
    Refresh: 'रीफ्रेश',
    'No guardian events yet.': 'अभी कोई गार्जियन घटना नहीं.',
    'Geofence Breach Detected': 'जियोफेंस उल्लंघन मिला',
    'View on Map': 'मानचित्र पर देखें',
    'Last Known Location': 'अंतिम ज्ञात स्थान',
    Live: 'लाइव',
    Heading: 'दिशा',
    Distance: 'दूरी',
    'View Live Tracking': 'लाइव ट्रैकिंग देखें',
    'Geofence Breach Alert': 'जियोफेंस उल्लंघन अलर्ट',
    'Outside Safe Zone': 'सुरक्षित क्षेत्र से बाहर',
    'Your vehicle has moved outside the safe zone.': 'आपका वाहन सुरक्षित क्षेत्र से बाहर चला गया है.',
    'Outside Since': 'बाहर कब से',
    'Outside By': 'कितना बाहर',
    'How Guardian Mode Works': 'गार्जियन मोड कैसे काम करता है',
    'Configure now': 'अभी कॉन्फ़िगर करें',
  },
};
